name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: The reference or tag
      java:
        required: true
        description: The build java version

jobs:
  publish:
    name: Publish Mindustry and Arc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: xpdustry-helper

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ github.event.inputs.java }}

      - name: Checkout Mindustry
        uses: actions/checkout@v4
        with:
          repository: 'Anuken/Mindustry'
          ref: ${{ github.event.inputs.version }}
          path: Mindustry

      - name: Checkout Arc
        uses: actions/checkout@v4
        with:
          repository: 'Anuken/Arc'
          ref: ${{ github.event.inputs.version }}
          path: Arc

      - name: Install and Setup Minio CLI
        run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc \
            --create-dirs \
            -o $HOME/minio-binaries/mc

          chmod +x $HOME/minio-binaries/mc
          export PATH=$PATH:$HOME/minio-binaries/

          bash +o history
          mc alias set xpdustry https://minio1.xpdustry.com $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
          bash -o history

          mc cp -r xpdustry/maven-anuken-releases/ ~/.m2/repository
        env:
          MINIO_ACCESS_KEY: "${{ secrets.MINIO_ACCESS_KEY }}"
          MINIO_SECRET_KEY: "${{ secrets.MINIO_SECRET_KEY }}"

      - name: Build, Test and Install Mindustry and Arc
        run: |
          cd ./Arc
          echo ";apply plugin: 'maven-publish';" >> ./build.gradle
          ./gradlew build install
          cd ../Mindustry
          echo ";apply plugin: 'maven-publish';" >> ./build.gradle
          ./gradlew build install

      - name: Upload Updated Artifacts to S3
        run: |
          # Upload the updated artifacts to S3
          mc cp -r ~/.m2/repository/* xpdustry/maven-anuken-releases/
