name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: The reference or tag
      java:
        required: true
        description: The build java version

jobs:
  publish:
    name: Publish Mindustry and Arc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: xpdustry-helper

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ github.event.inputs.java }}

      - name: Checkout Mindustry
        uses: actions/checkout@v4
        with:
          repository: 'Anuken/Mindustry'
          ref: ${{ github.event.inputs.version }}
          path: mindustry

      - name: Checkout Arc
        uses: actions/checkout@v4
        with:
          repository: 'Anuken/Arc'
          ref: ${{ github.event.inputs.version }}
          path: arc
      
      - name: Set up Xpdustry Repository
        run: |
          cat ./xpdustry-helper/scripts/publish.gradle >> ./mindustry/build.gradle
          cat ./xpdustry-helper/scripts/publish.gradle >> ./arc/build.gradle

      - name: Build, Test and Publish Mindustry and Arc
        env:
          ORG_GRADLE_PROJECT_xpdustryUsername: "${{ secrets.XPDUSTRY_MAVEN_USERNAME }}"
          ORG_GRADLE_PROJECT_xpdustryPassword: "${{ secrets.XPDUSTRY_MAVEN_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.XPDUSTRY_MAVEN_SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.XPDUSTRY_MAVEN_SIGNING_PASSWORD }}"
        run: |
          cd ./mindustry 
          ./gradlew jar test publishMavenPublicationToXpdustryRepository
          cd ../arc
          ./gradlew jar test publishMavenPublicationToXpdustryRepository
